#!/usr/bin/env python3
"""Audit and export Lapce's translation catalog.

The application uses TOML locale files and a small Rust/Floem wrapper rather
than a framework-specific extraction format.  This script provides one stable
view over the two sources of translatable text that can be checked reliably:

* literal keys used by ``I18n::text``/``text_signal``;
* settings metadata declared by ``#[field_names(desc = ...)]``.

It intentionally does not treat user content, paths, diagnostics, plugin
metadata, command IDs, or configuration values as translatable text.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterable

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.10 fallback
    print("i18n_audit.py requires Python 3.11+ (tomllib)", file=sys.stderr)
    raise


ROOT = Path(__file__).resolve().parents[1]
LOCALE_DIR = ROOT / "lapce-app" / "assets" / "locales"
EN_PATH = LOCALE_DIR / "en.toml"
ZH_PATH = LOCALE_DIR / "zh-CN.toml"

CONFIG_KINDS = ("core", "editor", "ui", "terminal")
CONFIG_FIELDS = re.compile(
    r"#\[field_names\((?P<attrs>.*?)\)\]\s*"
    r"(?P<visibility>pub\s+)?(?P<field>[A-Za-z_][A-Za-z0-9_]*)\s*:",
    re.DOTALL,
)
CONFIG_STRUCT = re.compile(
    r"pub\s+struct\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\{(?P<body>.*?)\n\}",
    re.DOTALL,
)
I18N_KEYS = re.compile(
    r"\b(?:text|text_signal)\(\s*\"(?P<key>[A-Za-z0-9_.-]+)\""
)


def parse_locale(path: Path) -> dict[str, str]:
    with path.open("rb") as source:
        data = tomllib.load(source)
    return {str(key): str(value) for key, value in data.items()}


def kebab(field: str) -> str:
    return field.replace("_", "-")


def settings_entries() -> Iterable[tuple[str, str, str]]:
    for kind in CONFIG_KINDS:
        source = ROOT / "lapce-app" / "src" / "config" / f"{kind}.rs"
        text = source.read_text(encoding="utf-8")
        struct_name = f"{kind.title()}Config"
        struct = next(
            (match for match in CONFIG_STRUCT.finditer(text) if match.group("name") == struct_name),
            None,
        )
        if struct is None:
            continue
        for match in CONFIG_FIELDS.finditer(struct.group("body")):
            attrs = match.group("attrs")
            if "skip" in attrs:
                continue
            field = kebab(match.group("field"))
            desc_match = re.search(r'desc\s*=\s*"((?:\\.|[^"\\])*)"', attrs)
            if not desc_match:
                continue
            description = bytes(desc_match.group(1), "utf-8").decode(
                "unicode_escape"
            )
            base = f"settings.item.{kind}.{field}"
            yield f"{base}.name", kind, field
            yield f"{base}.description", kind, field


def source_keys() -> set[str]:
    keys: set[str] = set()
    for source in (ROOT / "lapce-app" / "src").rglob("*.rs"):
        text = source.read_text(encoding="utf-8")
        keys.update(match.group("key") for match in I18N_KEYS.finditer(text))
    return keys


def catalog_rows(en: dict[str, str], zh: dict[str, str]) -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for key in sorted(en):
        english = en[key]
        chinese = zh.get(key, "")
        if key.startswith("settings.item."):
            category = "settings"
        elif key.startswith("command."):
            category = "commands"
        else:
            category = key.split(".", 1)[0]
        if key not in zh:
            status = "missing"
        elif english == chinese and key not in {
            "menu.app",
            "settings.language.en",
            "settings.value.language.en",
            "settings.language.zh-cn",
            "settings.value.language.zh-CN",
        }:
            status = "same-as-en"
        else:
            status = "ok"
        rows.append((key, category, english, chinese, status))
    return rows


def write_catalog(path: Path, rows: list[tuple[str, str, str, str, str]]) -> None:
    lines = [
        "# Translation catalog (generated)",
        "",
        "Do not edit this file directly. Run `python scripts/i18n_audit.py --write-catalog docs/i18n-catalog.md`.",
        "",
        "| Key | Category | English | 简体中文 | Status |",
        "| --- | --- | --- | --- | --- |",
    ]
    for key, category, english, chinese, status in rows:
        def cell(value: str) -> str:
            return value.replace("|", "\\|").replace("\n", "<br>")

        lines.append(
            f"| `{cell(key)}` | {cell(category)} | {cell(english)} | "
            f"{cell(chinese)} | {status} |"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write-catalog",
        type=Path,
        help="write a generated Markdown translation table to this path",
    )
    args = parser.parse_args()

    en = parse_locale(EN_PATH)
    zh = parse_locale(ZH_PATH)
    errors: list[str] = []

    if set(en) != set(zh):
        errors.extend(f"locale key mismatch: {key}" for key in sorted(set(en) ^ set(zh)))

    expected_settings = {key for key, _, _ in settings_entries()}
    missing_settings = sorted(expected_settings - set(zh))
    if missing_settings:
        errors.extend(f"missing settings translation: {key}" for key in missing_settings)

    for key in sorted(expected_settings & set(zh)):
        value = zh[key]
        if not re.search(r"[\u3400-\u9fff]", value):
            errors.append(f"settings translation contains no Chinese text: {key}")

    referenced = source_keys()
    missing_references = sorted(referenced - set(en))
    if missing_references:
        errors.extend(f"missing referenced translation key: {key}" for key in missing_references)

    rows = catalog_rows(en, zh)
    if args.write_catalog:
        write_catalog(args.write_catalog, rows)

    print(f"locale keys: en={len(en)} zh-CN={len(zh)}")
    print(f"settings metadata keys: {len(expected_settings)}")
    print(f"literal i18n keys found in Rust: {len(referenced)}")
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("i18n audit: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
